In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
history = pd.read_csv('R:\\H.H.H\\FIFA  WORLD CUP 2026\\Historical data\\FIFA World Cup 1930-2022 All Match Dataset.csv',
                      encoding='latin-1')
rankings = pd.read_csv('R:\\H.H.H\\FIFA  WORLD CUP 2026\\fifa ranks\\clean_ranks.csv')

In [ ]:
history.columns 
# history.copy()

Index(['Key Id', 'Tournament Id', 'tournament Name', 'Match Id', 'Match Name',
       'Stage Name', 'Group Name', 'Group Stage', 'Knockout Stage', 'Replayed',
       'Replay', 'Match Date', 'Match Time', 'Stadium Id', 'Stadium Name',
       'City Name', 'Country Name', 'Home Team Id', 'Home Team Name',
       'Home Team Code', 'Away Team Id', 'Away Team Name', 'Away Team Code',
       'Score', 'Home Team Score', 'Away Team Score', 'Home Team Score Margin',
       'Away Team Score Margin', 'Extra Time', 'Penalty Shootout',
       'Score Penalties', 'Home Team Score Penalties',
       'Away Team Score Penalties', 'Result', 'Home Team Win', 'Away Team Win',
       'Draw'],
      dtype='str')

In [ ]:
history['date'] = pd.to_datetime(history['Match Date'], errors='coerce')
history['year'] = history['date'].dt.year
history['total_score'] = history['Home Team Score'] + history['Away Team Score']
columns_to_keep = ['date','year','Home Team Name',
       'Home Team Code','Away Team Name', 'Away Team Code',
       'Home Team Score', 'Away Team Score', 'Home Team Score Margin',
       'Away Team Score Margin','Result', 'Home Team Win', 'Away Team Win',
       'Draw']
history = history[columns_to_keep]
history.head()

,date,year,Home Team Name,Home Team Code,Away Team Name,Away Team Code,Home Team Score,Away Team Score,Home Team Score Margin,Away Team Score Margin,Result,Home Team Win,Away Team Win,Draw
0,1930-07-13,1930,France,FRA,Mexico,MEX,4,1,3,-3,home team win,1,0,0
1,1930-07-13,1930,United States,USA,Belgium,BEL,3,0,3,-3,home team win,1,0,0
2,1930-07-14,1930,Yugoslavia,YUG,Brazil,BRA,2,1,1,-1,home team win,1,0,0
3,1930-07-14,1930,Romania,ROU,Peru,PER,3,1,2,-2,home team win,1,0,0
4,1930-07-15,1930,Argentina,ARG,France,FRA,1,0,1,-1,home team win,1,0,0

In [ ]:
#To attach rankings, matches started from 1992.
#so i need to split down historical data

deep_history = history[history['year'] < 1992]
recent_history = history[history['year'] >= 1992]

In [ ]:
#merging recent history with team rankings from 1992-2024

,date,year,Home Team Name,Home Team Code,Away Team Name,Away Team Code,Home Team Score,Away Team Score,Home Team Score Margin,Away Team Score Margin,Result,Home Team Win,Away Team Win,Draw
464,1994-06-17,1994,Germany,DEU,Bolivia,BOL,1,0,1,-1,home team win,1,0,0
465,1994-06-17,1994,Spain,ESP,South Korea,KOR,2,2,0,0,draw,0,0,1
466,1994-06-18,1994,United States,USA,Switzerland,CHE,1,1,0,0,draw,0,0,1
467,1994-06-18,1994,Italy,ITA,Republic of Ireland,IRL,0,1,-1,1,away team win,0,1,0
468,1994-06-18,1994,Colombia,COL,Romania,ROU,1,3,-2,2,away team win,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959,2022-12-10,2022,England,ENG,France,FRA,1,2,-1,1,away team win,0,1,0
960,2022-12-13,2022,Argentina,ARG,Croatia,HRV,3,0,3,-3,home team win,1,0,0
961,2022-12-14,2022,France,FRA,Morocco,MAR,2,0,2,-2,home team win,1,0,0
962,2022-12-17,2022,Croatia,HRV,Morocco,MAR,2,1,1,-1,home team win,1,0,0
963,2022-12-18,2022,Argentina,ARG,France,FRA,3,3,0,0,home team win,1,0,0